environment:
    matrix:
        - target: msvc
          ver: 2013
          generator: "Visual Studio 12 2013 Win64"
          configuration: Release
        - target: msvc
          ver: 2015
          generator: "Visual Studio 14 2015 Win64"
          configuration: Debug
        - target: msvc
          ver: 2015
          generator: "Visual Studio 14 2015 Win64"
          configuration: Release
        - target: mingw
          generator: "Unix Makefiles"

matrix:
  fast_finish: true

platform:
    - x64

install:
    - git submodule update --init --recursive
    # MinGW
    - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
    - gcc -v
    - ls -l C:\

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - ps: |
          Invoke-WebRequest https://github.com/google/googletest/archive/release-1.7.0.zip -OutFile release-1.7.0.zip
          7z x release-1.7.0.zip
          Rename-Item -Path googletest-release-1.7.0 -NewName gtest

    - if /i "%target%" == "msvc" (
        cd gtest &&
        cmake . -G"%generator%" -DCMAKE_CONFIGURATION_TYPES="Release;Debug;" &&
        msbuild gtest.sln &&
        mkdir lib &&
        move %configuration%\gtest.lib lib\gtest.lib &&
        move %configuration%\gtest_main.lib lib\gtest_main.lib &&
        cd .. &&
        del release-1.7.0.zip &&
        mkdir build_msvc%ver% &&
        cd build_msvc%ver% &&
        cmake .. -G"%generator%" -DCMAKE_CONFIGURATION_TYPES="Release;Debug;" -DGTEST_ROOT=%cd%\..\gtest &&
        msbuild dmlc.sln
      )
    - if /i "%target%" == "mingw" (
        cd gtest &&
        cmake . -G"%generator%" &&
        make -j2 &&
        mkdir lib &&
        move libgtest.a lib\libgtest.a &&
        move libgtest_main.a lib\libgtest_main.a &&
        cd .. &&
        del release-1.7.0.zip &&
        mkdir build_mingw &&
        cd build_mingw &&
        cmake .. -G"%generator%" -DGTEST_ROOT=%cd%\..\gtest &&
        make -j2
      )

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - if /i "%target%" == "msvc" (
        .\build\test\unittest\%configuration%\dmlc_unit_tests.exe
      )
    - if /i "%target%" == "mingw" (
        .\build\test\unittest\dmlc_unit_tests.exe
      )
